import "./styles/styles.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="page-top">
        {/* Custom JS files */}
        <script
          async
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        ></script>
        {/* theme js */}
        <script async src="/js/scripts.js"></script>
        {/* startbootstrap forms */}
        <script
          async
          src="https://cdn.startbootstrap.com/sb-forms-latest.js"
        ></script>
        {children}
      </body>
    </html>
  );
}
